### ISSUE TITLE
Some bugs regarding time

### ISSUE THREAD

**Issue by antonjarl** [DSorlov/hasl-platform#1]
I seen some bugs with the lovelace card and time updates. This is just one example, I've seen more of these.

So in this example, the train from Fruängen actually has already left, but it still says "2 min" even though the card clearly updated after the train left.
Also, the switch between fixed time (**14:29**) and timeTo (**5 min**) seems to be a little bit buggy as well.
I've seen those being mixed and in different order.

I'm happy to help you sorting this but my Python skills are limited.
![11 - ppd3xt772o](https://user-images.githubusercontent.com/10976586/52565784-21036f00-2e08-11e9-8490-c2f58fc7515f.png)

**Comment by lokanx** [comment]
The 14:19, 14:29 thing is actually a result of how SL API works. From https://www.trafiklab.se/node/15754/documentation


Namn | Datatyp | Beskrivning
-- | -- | --
DisplayTime | String | Avgångstid för presentation. Kan anta formaten x min, HH:mm eller Nu. Om det finns tillhörande störning med tillräckligt hög prioritet så kan denna ha värdet ”-”. Detta fram till ett par minuter innan avgång.Tunnelbana före övergång:Beräknad avgång från hållplatsen, t.ex. ”2 min” eller ”Nu”.

**Comment by DSorlov** [comment]
This is as @lokanx said above by design from api. Will not be adressed currently atleast as the aim is a very low impact implementation and not working the data to hard.

**Comment by DSorlov** [comment]
Some updates have not been made in how this is displayed. Please see changelog.

**Comment by antonjarl** [comment]
Thanks for the update. I'll try it!
