### ISSUE TITLE
Wrong time shown

### ISSUE THREAD

**Issue by folrewef** [DSorlov/hasl-platform#11]
I get a strange phenomenon where the departure time shown in the card is two hours later than the actual departure time. At the same time the latest updated time is correct.

![Skärmavbild 2019-04-16 kl  10 11 55](https://user-images.githubusercontent.com/43371683/56193268-88b87f00-6030-11e9-8075-9029ccde1e40.png)

**Comment by DSorlov** [comment]
Could this be to a timezone issue of some kind? I have not been able to recreate this. Are your timezone settings wrong at os-level? There is a slight difference in how the numbers are crunched when it comes to times displayed (as one is locally generated and the other is remote)

**Comment by folrewef** [comment]
Thanks for your reply and sorry I was so slow to get back. I verified my time settings using the time & date sensor. I get time is current time in my time zone and time_utc as current time minus two hours which is correct. That indicates that I have the correct time settings. 

I look at the system information (hassOS 2.11) that reports events in time utc. I see nothing that explains why the card displays time etc plus four hours.

**Comment by folrewef** [comment]
I get this error upon start up. I do not know if it can be related?

> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 230, in async_add_entities
>     self.hass, self._update_entity_states, self.scan_interval
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/event.py", line 254, in async_track_time_interval
>     hass, interval_listener, next_interval())
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/event.py", line 243, in next_interval
>     return dt_util.utcnow() + interval
> TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'str'

**Comment by folrewef** [comment]
And a final interesting data point. When using
timeleft: true
I get the right information (a few minutes and not 2 hours + a few minutes!

**Comment by DSorlov** [comment]
I know you have been fighting some with getting this to work; what is the status on the issue described in this issue in regards to issue #14 ?

**Comment by isabellaalstrom** [comment]
Same problem, same fix?
https://github.com/home-assistant/home-assistant/pull/23284

**Comment by folrewef** [comment]
I an sorry. No direct success here but Isabella’s lead seems worthwhile exploring.

**Comment by DSorlov** [comment]
> Same problem, same fix?
> [home-assistant/home-assistant#23284](https://github.com/home-assistant/home-assistant/pull/23284)

Yes, seems very valid and makes sense. Have tried to muck about with this and have been able to both recreate the error and this solution seems to fix it.

It is checked in to dev branch right now and will be in release 1.0.4
