### ISSUE TITLE
Missing data in frontend, but logs looks good

### ISSUE THREAD

**Issue by TheRealLouCipher** [DSorlov/hasl-platform#13]
Looking at the sensor in the frontend and it's missing data.

`attribution: Stockholms Lokaltrafik`
`unit_of_measurement: min`
`next_departure_minutes: 1`
`next_departure_expected: 11:55:28`
`departures: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]`
`deviations: `
`last_refresh: 2019-04-17 11:54:04`
`refresh_enabled: on`
`friendly_name: Vanadisvägen`
`icon: mdi:train-car`

looking in the debug log the sensor seems the contain data but that is not seen in the frontend.. 

`2019-04-17 11:54:04 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139664284034664] Sending {'id': 2, 'type': 'event', 'event': <Event state_changed[L]: entity_id=sensor.vanadisvagen, old_state=<state sensor.vanadisvagen=3; attribution=Stockholms Lokaltrafik, unit_of_measurement=min, next_departure_minutes=3, next_departure_expected=11:47:41, departures=[{'line': '2', 'direction': 2, 'departure': '3 min', 'destination': 'Norrtull', 'time': 3, 'expected': '2019-04-17T11:47:41', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 1, 'departure': '5 min', 'destination': 'Sofia', 'time': 5, 'expected': '2019-04-17T11:49:22', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 2, 'departure': '12 min', 'destination': 'Norrtull', 'time': 12, 'expected': '2019-04-17T11:56:40', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 1, 'departure': '11:58', 'destination': 'Sofia', 'time': 15, 'expected': '2019-04-17T11:58:22', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 2, 'departure': '22 min', 'destination': 'Norrtull', 'time': 22, 'expected': '2019-04-17T12:06:27', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 1, 'departure': '23 min', 'destination': 'Sofia', 'time': 23, 'expected': '2019-04-17T12:07:22', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 2, 'departure': '29 min', 'destination': 'Norrtull', 'time': 29, 'expected': '2019-04-17T12:13:30', 'type': 'Buses', 'icon': 'mdi:bus'}], deviations=[], last_refresh=2019-04-17 11:43:47, refresh_enabled=on, friendly_name=Vanadisvägen, icon=mdi:train-car @ 2019-04-17T11:43:47.420489+02:00>, new_state=<state sensor.vanadisvagen=1; attribution=Stockholms Lokaltrafik, unit_of_measurement=min, next_departure_minutes=1, next_departure_expected=11:55:28, departures=[{'line': '2', 'direction': 2, 'departure': '1 min', 'destination': 'Norrtull', 'time': 1, 'expected': '2019-04-17T11:55:28', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 1, 'departure': '11:58', 'destination': 'Sofia', 'time': 4, 'expected': '2019-04-17T11:58:22', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 2, 'departure': '12 min', 'destination': 'Norrtull', 'time': 12, 'expected': '2019-04-17T12:06:42', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 1, 'departure': '13 min', 'destination': 'Sofia', 'time': 13, 'expected': '2019-04-17T12:07:22', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 2, 'departure': '18 min', 'destination': 'Norrtull', 'time': 18, 'expected': '2019-04-17T12:12:52', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 1, 'departure': '21 min', 'destination': 'Sofia', 'time': 21, 'expected': '2019-04-17T12:15:22', 'type': 'Buses', 'icon': 'mdi:bus'}, {'line': '2', 'direction': 2, 'departure': '27 min', 'destination': 'Norrtull', 'time': 27, 'expected': '2019-04-17T12:21:12', 'type': 'Buses', 'icon': 'mdi:bus'}], deviations=[], last_refresh=2019-04-17 11:54:04, refresh_enabled=on, friendly_name=Vanadisvägen, icon=mdi:train-car @ 2019-04-17T11:54:04.965171+02:00>>}`

I'm using version 1.0.3 of sensor.py
HA version 0.91.4
My sensor config

`- platform: sl`
`  ri4key: !secret sl_ri4key`
 ` si2key: !secret sl_si2key`
 ` siteid: 1074`
 ` friendly_name: Vanadisvägen`
 ` lines: 2`
`#  direction: 1`
`#  sensor: binary_sensor.sl_update`

**Comment by DSorlov** [comment]
What is the missing data? I'm not sure I can follow? =) Sorry for not getting it but will be glad to help once I know where to look.. =)

**Comment by TheRealLouCipher** [comment]
I dev-state the sensor looks like this, departures listed as departures: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

<img width="906" alt="Skärmavbild 2019-04-18 kl  14 30 00" src="https://user-images.githubusercontent.com/41365311/56361105-d4ad2480-61e6-11e9-8ad1-214177568b48.png">

But in the logs I see data for Departures.

**Comment by DSorlov** [comment]
Ah, when you look at in the dev-state it will look like this. It is a limitation in the GUI for the dev-state view (it cannot see into and render complex objects). Use the custom card sl-card.js (or make a similar one yourself) to display the actual data. This is very much like many of the weather sensors that are out there. The property that is default is the next_departure_minutes.

**Comment by TheRealLouCipher** [comment]
Ah, why didn't I test with the card. Works perfectly now! Thank you for your help and great work!

**Comment by DSorlov** [comment]
No worries! Let me know if any problems arises!
