### ISSUE TITLE
scan_interval not working (and some other stuff)

### ISSUE THREAD

**Issue by nesalkiN** [DSorlov/hasl-platform#20]
Using scan_interval makes the "Senast uppdaterad" update at least every minute. Always -1 or 0 min since last updated. The time shown is always the current time +- 1 min. Bug? Calling the api every minute or display error? I used scan_interval: 7. Should it be in min or sec?

Btw, always show time, was that removed?

The card does not look like the other cards? No box? (note the update time, 0 min)
![Capture_Home_Assistant_-_Google_Chrome_2019-04-30_20-09-18_18455232](https://user-images.githubusercontent.com/4583709/56983415-de8a3c80-6b83-11e9-9e41-f06b2638763b.png)

**Comment by hekm77** [comment]
> The card does not look like the other cards? No box?

I can confirm. There is a problem with _paper-card-background-color_

<img width="527" alt="111" src="https://user-images.githubusercontent.com/22895433/56984246-e34ff000-6b85-11e9-9ee8-98140deae0a0.png">

**Comment by DSorlov** [comment]
scan_interval is a time so that should be for instance like below. If you just specify a intervall with a integer that seems to be translated into seconds and that would then be 420.
```
scan_interval:
      hours: 0
      minutes: 7
      seconds: 0
```

The other part of the problem would be perhaps around the card. I cannot reproduce that error. I do have a frame as it looks in the readme, I'm using the below. Would that not give a frame in your end?
```
adjust_times: true
departures: true
deviations: true
entities:
  - sensor.molnvik_departures
language: sv-SE
name: Mölnvik
timeleft: true
type: 'custom:hasl-dep-card'
updated: true
```

**Comment by hekm77** [comment]
> The other part of the problem would be perhaps around the card.

`const card = document.createElement('ha-card');`

This fixes a bug with the card in line 4 [hasl-comb-card.js](https://github.com/DSorlov/ha-sensor-sl/blob/hasl/www/hasl-comb-card.js#L4)

**Comment by DSorlov** [comment]
This have been updated/reverted in dev #22
