### ISSUE TITLE
default scan_interval still 10 minutes

### ISSUE THREAD

**Issue by folrewef** [DSorlov/hasl-platform#24]
The default scan interval is still 10 minutes:

# Default values for configuration
DEFAULT_INTERVAL=timedelta(minutes=10)

**Comment by DSorlov** [comment]
Will update documentation to reflect the default_interval

**Comment by folrewef** [comment]
Thanks for your great work! Really happy with this component.

**Comment by folrewef** [comment]
Fri, I had to set scan_interval to 300 (5*60) to get 5 minute updates.

**Comment by DSorlov** [comment]
So it did not work with?

scan_interval:
       hours: 0
       minutes: 7
       seconds: 10

**Comment by folrewef** [comment]
That could probably also work. 
The way the readme is worded it can seem as if it should be
scan_interval: 5
Probably this also works:
scan_interval: 00:05:00

**Comment by erikatl** [comment]
Sorry to barge in here, I also had problem setting the scan_interval correctly. After reading this, I tried all of the above-mentioned tips, and seem to have understood that you have to set it in seconds, not minutes. My problem is that by doing that I seem to have wasted my month's share of API calls, so right after having found which method is working I am now locked out... I hope you guys can confirm or deny my finds.

**Comment by hekm77** [comment]
You can see API-statistik in your Trafiklab profile 
https://www.trafiklab.se/user/XXXXX/api-stats

**Comment by erikatl** [comment]
@hekm77 It might have been a hickup, the service is on again, at a sensible rate. I chose "scan_interval: 900" as I have 3 sensors (commuter trains southbound, commuter trains northbound and buses). 900 as in 15 minutes, for 3 sensors it should theoretically keep me in safe territory.

**Comment by DSorlov** [comment]
Remember also if the departing station have same id that will only be one call regardless of how many sensors use it. It polls all the information to the local cache and the filters.

Also documentation will be fixed (is fixed in dev) and will be changed as soon as I push dev to main.

**Comment by erikatl** [comment]
@DSorlov Thank you for the clarification. I will change the setting to 300 then.

**Comment by erikatl** [comment]
Maybe I should post this as a new issue, it might have something to do with my setup with 3 sensors? I noticed that not all of my sensors get updated when they should. Sometimes 2 out of three of the sensors are more than an hour old. So I checked the log and it is full of error messages such as this: 
"Update for sensor.helenelund_pendeltag_norrut fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/hasl/sensor.py", line 468, in _update
    departuredata = getCache(self._ri4datakey)
NameError: name 'getCache' is not defined"

**Comment by DSorlov** [comment]
Please open new issue. I did however already verify it and it must be due to me beeing stupid to have made that typo in my cleanup... *should test more* but ooen a new issue and I will start coding a fix.. :)

**Comment by erikatl** [comment]
Done. :-)

**Comment by DSorlov** [comment]
Fixed and released in 2.1.0
