### ISSUE TITLE
Browser och app visar olika tider

### ISSUE THREAD

**Issue by pofferoffe** [DSorlov/hasl-platform#26]
I Hass.io 0.92.2 visas bussavgång kl 18:24, 18:36, osv. I Home Assistant **appen** (iOS) är de förskjutna 2 timmar, så att samma avgångar visas som 20:24, 20:36, osv. I båda visas samma klockslag/tidstämpel för när värdet uppdaterades, tex 18:22. Någon idé varför? Har kollat tiden på burken jag kör Hass.io på, samt telefonen. De visar samma tid... Kan lägga till att om jag surfar in till HA via en webbläsare på en telefon (iOS), får jag samma symptom; tiden förskjuts två timmar. Alltså enbart om jag surfar in via en dators webbläsare det visas rätt. Hassio och datorn den körs på har samma tidzon, Europe/Stockholm.

**Comment by ekesa** [comment]
i have a simular issue, HA app, iOS browser (safari) and firefox on Mac also showing +2h for me.

**Comment by DSorlov** [comment]
@pofferoffe As I have a hard time reproducing this could you check the actual values in the sensor to determine if this is a front-end or back-end problem with the sensor?

**Comment by ekesa** [comment]
Hi,

Maybe i can give you some input here.

On my iphone (HA app), where i have the problem with +2h on departure:
Real time is now 10:23
Next departure for bus 402 is 12:31 and 12:38 according to app.
If i check the sensor it says departure 10:31 and 10:38 which is correct.

Br
Fredric

**Comment by DSorlov** [comment]
This sounds very much like something then that is transforming the date in the GUI?

**Comment by dimmanramone** [comment]
I haven't been able to reproduce that in an android device, chrome os and windows (chrome and firefox). I have to get my hands on a mac and iPhone to investigate further. @ekesa Can you check the timezone and language settings in both your mac and iPhone, as well as check if there are timezone and language settings in your browser (safari and firefox)? It would be easier for me to reproduce.

**Comment by Pliind** [comment]
I had a similar issue with my calendar extension. Make sure your server is on the correct time-zone. After editing this my times started showing correct.

**Comment by Maximus97** [comment]
Having the same issue, the app and the web browser on my ipad shows the time with +2h offset. 

@Pliind Could you be more specific? Exacly what time did you edit? Your servers operating systems timezone?

**Comment by Pliind** [comment]
@maximus97 on the run right now but i edited the /etc/localtime file.

**Comment by Maximus97** [comment]
Hmm I don't even have that file and I'm running Hassio on rpi

**Comment by dimmanramone** [comment]
@Pliind @Maximus97 I finally got my hands on an iPhone. Just tested in Chrome and it is +2 hours in iOS. Checked the timezone settings in both my host os and on hassio docker and it is the right ones. Still iOS is showing wrong time. As I wrote before, Chrome OS, Windows and Android works fine. I'll investigate more.

**Comment by dimmanramone** [comment]
@Maximus97 Do you use timeleft and adjust_times? And what's your language in the card configuration?

**Comment by Maximus97** [comment]
@dimmanramone thanks for taking your time to investigate this. I am not using timeleft or adjust_times. I am using swedish in my card configuration.

**Comment by dimmanramone** [comment]
@Maximus97 I have to investigate a little bit more  and get my hands in a mac :) It's a strange bug. Right now it seems that it is not a GUI bug but it doesn't seem to be something wrong the either :/

**Comment by DSorlov** [comment]
If you look at the config page in home assistant. Is it the correct timezone there?
![Capture](https://user-images.githubusercontent.com/8133650/61580216-9db11c80-ab0f-11e9-945f-c595b266e4ef.PNG)

**Comment by dimmanramone** [comment]
@DSorlov It is a realIy strange bug. I have the right timezone and everything works fine in android/windows/linux in any browser. Though when I tested in iOS and MacOS i get +2h in the GUI. Unfortunatelly I don't own a iPhone or a MAC to test more and debug the js to see the values that it gets from the sensor.

**Comment by DSorlov** [comment]
Aha. I think I have a old macbook somewhere I could try and ressurect.. #dangerzone #excorsism #blackmagic

**Comment by dimmanramone** [comment]
@DSorlov sounds good :) You can even test this to see if you get the write time https://playcode.io/381885?tabs=script.js,preview,console

**Comment by Maximus97** [comment]
Has there been any progress made on this?

**Comment by dimmanramone** [comment]
@Maximus97 Unfortunately not, I'm on holidays so I didn't have the chance to look into it more. I don't know if @DSorlov had the time to do that?

**Comment by Maximus97** [comment]
Setting `timeleft` to `true` in the card config seems to solve the issue for me.

**Comment by Maximus97** [comment]
@pofferoffe @ekesa see my comment

**Comment by DSorlov** [comment]
I have still not been able to reproduce it even om my mac.. :/ we need to try and triage this in a good way. Any settings that are special like locale or similar?

**Comment by DSorlov** [comment]
Due to the major rewrite that is happening for v3 this issue will be closed but we will look at it to make sure v3 does not suffer from same issues.
