### ISSUE TITLE
Showing incorrect lines

### ISSUE THREAD

**Issue by theGurk** [DSorlov/hasl-platform#3]
If you choose Odenplan as station (siteid:1079) and then add line 43 (which is the "Pendel-tåg") you will also get line 4 (the bus) even thou you haven´t stated that. Do you have any fix for this?

**Comment by DSorlov** [comment]
Yes, this have been missed. Will be adressed in next update.

**Comment by DSorlov** [comment]
This now seems fixed in version 0.0.8, cannot repro for now atleast.
