### ISSUE TITLE
Platform not found: sensor.hasl

### ISSUE THREAD

**Issue by PHagenfeldt** [DSorlov/hasl-platform#36]
Hi,

I'm having issues getting hasl to work.

I have installed it via HACS and the installation seems to work since I have a hasl folder. However, when trying to add the configuration and validating it I get the "Platform not found: sensor.hasl" error. 

I have had the same issue with my previous set up so I bought a new SD card and made a fresh install of Hassbian. 

The only error I get in HA log is: "You are using a custom integration for hasl which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
14:37 loader.py (WARNING)"

I have version 0.95.4 on HA.

**Comment by DSorlov** [comment]
Yes, this have now been confirmed, it is a known issue and fix is on its way!

**Comment by DSorlov** [comment]
If anyone could confirm it now works (using the dev branch), seems to work for me now.

**Comment by PHagenfeldt** [comment]
> If anyone could confirm it now works (using the dev branch), seems to work for me now.

Not sure if I did it correctly but still getting the same error.

Not sure if it's possible to download the dev branch in HACS so I changed to the dev branch in GitHub , downloaded the files in custom_components and replaced them in my config. I have both rebooted HA and my RPI.

**Comment by dimmanramone** [comment]
@PHagenfeldt I guess HACS just works with the stable hasl branch. So you did right. Can you see anything in your log? Can you check in developer tools under states that you don't see your sensor?

For me was working with 0.95.4 and still works with 0.96

**Comment by PHagenfeldt** [comment]
> @PHagenfeldt I guess HACS just works with the stable hasl branch. So you did right. Can you see anything in your log? Can you check in developer tools under states that you don't see your sensor?
> 
> For me was working with 0.95.4 and still works with 0.96

Only the custom component error like before. Nothing under states and still the same error. Can't validate the config so trying to reboot through SSH but the sensor are still not showing. I'm still on 0.95.4.

**Comment by dimmanramone** [comment]
@PHagenfeldt Can you post your configuration?

**Comment by PHagenfeldt** [comment]
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include themes.yaml
tts:
  - platform: google_translate
hacs:
  token: xx
discovery:
tellduslive:
  host: 192.168.1.224
homekit:
  filter:
    include_domains:
      - light
      - media_player
light:
  - platform: switch
    name: Bokhyllan
    entity_id: switch.bokhyllan
  - platform: switch
    name: Fönstret vid matbordet
    entity_id: switch.fonstret_vid_matbordet
  - platform: switch
    name: Hörnlampan i vardagsrummet
    entity_id: switch.hornlampan_i_vardagsrummet
  - platform: switch
    name: Pianot
    entity_id: switch.pianot
  - platform: switch
    name: TV bänken
    entity_id: switch.tv_banken
  - platform: switch
    name: Fönstret i vardagsrummet
    entity_id: switch.vardagsrumsfonstret 
sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: hasl
    ri4key: xx
    si2key: xx
    ti2key: xx
    sensors:
     - friendly_name: Mölnvik
       sensor_type: departures
       siteid: 4244
       lines: 474, 480C
       direction: 1
       sensor: binary_sensor.test
     - friendly_name: Trafikstatus
       sensor_type: status
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

**Comment by PHagenfeldt** [comment]
> # Configure a default setup of Home Assistant (frontend, api, etc)
> default_config:
> frontend:
> themes: !include themes.yaml
> tts:
> 
> * platform: google_translate
>   hacs:
>   token: xx
>   discovery:
>   tellduslive:
>   host: 192.168.1.224
>   homekit:
>   filter:
>   include_domains:
>   
>   * light
>   * media_player
>     light:
> * platform: switch
>   name: Bokhyllan
>   entity_id: switch.bokhyllan
> * platform: switch
>   name: Fönstret vid matbordet
>   entity_id: switch.fonstret_vid_matbordet
> * platform: switch
>   name: Hörnlampan i vardagsrummet
>   entity_id: switch.hornlampan_i_vardagsrummet
> * platform: switch
>   name: Pianot
>   entity_id: switch.pianot
> * platform: switch
>   name: TV bänken
>   entity_id: switch.tv_banken
> * platform: switch
>   name: Fönstret i vardagsrummet
>   entity_id: switch.vardagsrumsfonstret
>   sensor:
> * platform: yr
>   name: Weather
>   forecast: 24
>   monitored_conditions:
>   
>   * temperature
>   * symbol
>   * precipitation
>   * windSpeed
>   * pressure
>   * windDirection
>   * humidity
>   * fog
>   * cloudiness
>   * lowClouds
>   * mediumClouds
>   * highClouds
>   * dewpointTemperature
> * platform: hasl
>   ri4key: xx
>   si2key: xx
>   ti2key: xx
>   sensors:
>   
>   * friendly_name: Mölnvik
>     sensor_type: departures
>     siteid: 4244
>     lines: 474, 480C
>     direction: 1
>     sensor: binary_sensor.test
>   * friendly_name: Trafikstatus
>     sensor_type: status
>     group: !include groups.yaml
>     automation: !include automations.yaml
>     script: !include scripts.yaml

@DSorlov I xx:d out the tokens and keys and the spaces looks a bit weird copied in here.

**Comment by DSorlov** [comment]
@PHagenfeldt try and remove the
sensor: binary_sensor.test
line as there is no such sensor in the config

**Comment by PHagenfeldt** [comment]
Alright, copied the example and it was there. Have removed it but still get the same error I'm afraid.

<img width="478" alt="Skärmavbild 2019-07-18 kl  11 08 35" src="https://user-images.githubusercontent.com/52971740/61444883-8fff6980-a94c-11e9-9d4b-e21067e3de07.png">

**Comment by dimmanramone** [comment]
@DSorlov I was about to say exactly the same thing. @PHagenfeldt  And check the indentation on the following:
`group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml`

It seems like it is unde the sensor_type: status

**Comment by PHagenfeldt** [comment]
> @DSorlov I was about to say exactly the same thing. @PHagenfeldt And check the indentation on the following:
> `group: !include groups.yaml automation: !include automations.yaml script: !include scripts.yaml`
> 
> It seems like it is unde the sensor_type: status

I think the indentation looked weird in the paste. Have a look at the picture I posted, does it look correct there?

**Comment by dimmanramone** [comment]
@PHagenfeldt Remove the cache and restart you home assistant.

**Comment by PHagenfeldt** [comment]
> @PHagenfeldt Remove the cache and restart you home assistant.

I removed the files in __pycache__ and rebooted my RPI, still the same error I'm afraid.

**Comment by dimmanramone** [comment]
@PHagenfeldt It is tl2key not ti2key. It is wrong in the documentation.

Can you verify that is working if you change it in your configuration?

**Comment by mikaelgz5** [comment]
Thats it, tl2key fixed config error.

**Comment by fredrikbuchanan** [comment]
tl2key and updateing hasl to the latest version and updating HA to 0.96

**Comment by dimmanramone** [comment]
@DSorlov Just updated the documentation on dev branch. I guess we can close this issue.

**Comment by PHagenfeldt** [comment]
@dimmanramone For me it did not work only changing ti2key to tl2key, however updating to 0.96 seemed to do the trick. Good job!
