### ISSUE TITLE
lines in 2.1.3

### ISSUE THREAD

**Issue by hekm77** [DSorlov/hasl-platform#37]
The `lines:` is required?
I get an error if I don't specify `lines:`
HASL 2.1.3
HA 0.95.4
```
sensor:
  - platform: hasl
    ri4key: !secret ri4key
    si2key: !secret si2key
    tl2key: !secret tl2key
    sensors:
      - friendly_name: HASL
        sensor_type: departures
        siteid: !secret siteid
        direction: 2
        timewindow: 30
      - friendly_name: Trafikstatus
        sensor_type: status
```
```
Error while setting up platform hasl
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/hasl/sensor.py", line 127, in setup_platform
    config.get(CONF_USE_MINIMIZATION)
  File "/home/homeassistant/.homeassistant/custom_components/hasl/sensor.py", line 462, in __init__
    self._lines = lines.split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by DSorlov** [comment]
Yeah, looks like an error. Working on another fix also right now. Hopefullt fixed very soon.

**Comment by DSorlov** [comment]
If anyone could confirm it now works (using the dev branch), seems to work for me now.

**Comment by hekm77** [comment]
@DSorlov 
There are no errors in the log now, but I get an empty card if I don’t specify the lines.
If I specify a few lines, on the card I get only the first one from the list.

`lines: 422, 410, 409, 414`
<img width="505" alt="111" src="https://user-images.githubusercontent.com/22895433/61428453-6e898800-a922-11e9-9d2b-9d94f8dbaed0.png">

**Comment by DSorlov** [comment]
Ok! Now this shoud work in dev branch; I have tried with many, none and one. All works here.
Also! Note that the format of the line have changed to be correct formatted also ie:
`lines: ['123','456']`

**Comment by hekm77** [comment]
@DSorlov 
Works like a charm on 0.96.0
Thanks.
