### ISSUE TITLE
Version 2.2.0 doesn't pass validation

### ISSUE THREAD

**Issue by erikatl** [DSorlov/hasl-platform#40]
Maybe it's just me but after changing to HACS for updates, HASL doesn't "compile" (validation fails). One breaking change is mentioned for us who get notifications, the fact that "lines" has a new syntax. I changed that to no avail. Getting into the repository I found what I believe is another breaking change: "sensor_type" must be set to "departures". I changed that too, no luck. What else do I need to change?

**Comment by DSorlov** [comment]
Could you please post error and config?

The departures is the new setting since a couple of releases but tl2 etc is still supported for now atleast.

**Comment by erikatl** [comment]
`#hasl:
  - platform: hasl
    name: helenelund
    ri4key: !secret ri4key
    si2key: !secret si2key
    sensors:
    - friendly_name: "Helenelund, pendeltåg söderut"
      sensor_type: departures
      siteid: 9507
#      lines: 40, 41, 42, 40X, 41X, 42X
      lines: ['40', '41', '42', '40X', '41X', '42X']
      direction: 1
      scan_interval: 300
      timewindow: 60
    - friendly_name: "Helenelund, pendeltåg norrut"
      sensor_type: comb
      siteid: 9507
      lines: ['40','41','42','40X','41X','42X']
      direction: 2
      scan_interval: 300
      timewindow: 60
    - friendly_name: "Helenelund, bussar"
      sensor_type: comb
      siteid: 9507
      lines: ['523','528','178']
      scan_interval: 300
      timewindow: 60
`

**Comment by DSorlov** [comment]
Looks like line 3 name: helenelund is a error, should not prevent it from running but could be.. Comb or departures should work regardless..

**Comment by erikatl** [comment]
Oops, I still had "comb" for two of the three sensors. Changing to "departures" didn't help though. The validation error isn't helpful at all, all it says is that it fails...

**Comment by erikatl** [comment]
Why would "name: helenelund" be an error? I don't understand...

**Comment by DSorlov** [comment]
Looks like its under plattform and not a sensor...

**Comment by erikatl** [comment]
You mean it has to do with indentation?

**Comment by erikatl** [comment]
It used to work "before HACS"...

**Comment by DSorlov** [comment]
There is no name support for the plattform node just friendly_name for each sensor.

I dont know if it is the formatting that screws up the file. Is -platform: hasl posted under ther the sensor: node?

**Comment by erikatl** [comment]
- platform: hasl is right under sensor

**Comment by erikatl** [comment]
It worked fine until I "went HACS"...

**Comment by DSorlov** [comment]
Have you restarted ha? Did you delete the __pycache__ folder fron hasl folder in custom_compinents? 

Wich version are you using of ha?

HACS should not interfere in any way as it just a install system.

Did you get an error message?

**Comment by erikatl** [comment]
Yes I have restarted HA several times. And yes, I have deleted the contents in the pycahe folder (not the folder itself). I am still on 0.95.4 as long as I can't solve this problem. And the message from the validation is: 
"Konfigurationen är inte giltig
Platform not found: sensor.hasl"

**Comment by DSorlov** [comment]
Aha! Unclear of why but we had some getting to work when updating to 0.96.2

**Comment by erikatl** [comment]
So you recommend me to upgrade?

**Comment by DSorlov** [comment]
In #36 abother user got it to work by updating to 0.92 atleast.

**Comment by erikatl** [comment]
I will give it a try tomorrow. (I am on 0.95.4 though, not too shady...) God natt!

**Comment by erikatl** [comment]
So now I am on 0.96.2 and everything works as it should! Issue closed.
