### ISSUE TITLE
Combine diretions

### ISSUE THREAD

**Issue by jacoblo** [DSorlov/hasl-platform#43]
Thanks for the work :-)

I have an issue with line directions. At Fridhemsplan bus 54 is direction 1 towards city centre while bus 1 is direction 2. Solved by creating two sensors but unfortunately the HASL-cards show them separately, forcing them to be out of order.

Any way that I can get around this?

    sensors:
     - friendly_name: Fridhemsplan54
       sensor_type: departures
       siteid: 9115
       lines: ['54']
       direction: 1
     - friendly_name: Fridhemsplan1
       sensor_type: departures
       siteid: 9115
       lines: ['1']
       direction: 2

<img width="465" alt="CleanShot 2019-09-02 at 23 17 06@2x" src="https://user-images.githubusercontent.com/18484639/64133641-f2ff6f80-cdd7-11e9-9267-dab45291f91a.png">

**Comment by DSorlov** [comment]
`lines: [['1',2],['54',1]]` perhaps to be a logical way of adding it to config? I feel that I dont know how it would be very intuative.. any suggestions?

**Comment by jacoblo** [comment]
Me neither, to be honest :-)

But I think that would work and make sense if possible?

**Comment by zvebbo** [comment]
Loving hasl, but I have the same problem at Trekanten (1603), where the bus has direction 2 and the tram has direction 1, eventhough they're going in the same direction in real life. Any progress on this?

**Comment by ekurin** [comment]
Just to echo previously comments, I'm having the same problem with my stop. 

As for a solution, I think your config suggestion of defining direction per line would work. 
Another suggestion would be some kind of merge-option of the sensors into one card?

**Comment by DSorlov** [comment]
Due to that we have started dev on new version 3, this will not be addressed here. In the rewrite the system will be different in the way that it handles requests of this type without multiple sensors.
