### ISSUE TITLE
Answer to homeassistant.update_entity

### ISSUE THREAD

**Issue by fatuuse** [DSorlov/hasl-platform#45]
I tried to update the sensor manually with the homeassistant.update_entity service. 
It doesn't seem to respond on that. Maybe I'm wrong. If not is it possible to update the sensors manually with homeassistant.update_entity  service?

**Comment by fatuuse** [comment]
Now i use a binary sensor on times i want continues updates. But if i want to force a update another time or between scan_interval.

**Comment by DSorlov** [comment]
Yepp, will not work in current implementation. However a really good idea for next verwion, will definitly be implemented.

**Comment by DSorlov** [comment]
This have already been adressed in the design of v3 that is currently under ways. This ticket will be closed.
