### ISSUE TITLE
Turn off api calls during certain times of day

### ISSUE THREAD

**Issue by tomoqv** [DSorlov/hasl-platform#46]
Again, thanks for this functionality that I have been looking for a long time!
Another feature request by me:
Add the ability to turn off api calls during certain times of day. I have just requested a higher API level with SL Trafiklab, because I was adding up about 5 000 calls per day with my realtime API calls. I want updates for the tram I am using to be fairly frequent, i.e. 1 minute. Otherwise, I don't get timely information when the tram leaves every 5 or 6 minutes. Unfortunately, this adds up to 1,440 calls per day. With some more stations and buses, trains etc. it is very difficult to stay below the stipulated 10,000 calls per month on the Bronze level at Trafiklab.
They suggested I take a look at https://github.com/teppos/MMM-SL for some inspiration on spreading the API calls throughout the day.

**Comment by dimmanramone** [comment]
@tomoqv You can do that already with the binary sensor

https://community.home-assistant.io/t/sl-public-transport-information-sweden/17726/64?u=dimmanramone

**Comment by tomoqv** [comment]
Ok, good. And should the sensor be in the format
1) `sensor: binary_sensor.alleparken_refresh`
or
2) `sensor: alleparken_refresh`

Thanks!

**Comment by dimmanramone** [comment]
The first one is the right one. You can you an automation thats turns on/off the sensor bases on time.

**Comment by tomoqv** [comment]
Ok. Yup, perfect!
