### ISSUE TITLE
Any reason to not to convert this into a component thats a part of HA?

### ISSUE THREAD

**Issue by sweco-semhul** [DSorlov/hasl-platform#5]
Seems the hardest work is done, so any reasons not to convert this custom component into a component thats shipped as a part of HA?
https://developers.home-assistant.io/docs/en/creating_component_code_review.html

**Comment by DSorlov** [comment]
Ok. For some strange reson I will actually start the procedure of doing this. Will update once code is more stable for this and cleanup and other stuff performed. Speed could be somewhat low due to high worklife load at the moment however.

**Comment by sweco-semhul** [comment]
Nice to hear!
Was thinking about starting on it, but have had to much other things to do. So let me know if there is something I can help out with.

**Comment by DSorlov** [comment]
I have started a new branch called hasl with the backbone to the new code. it is "drycoded" on the train and not even close to beeing tested as I will be on the road for a couple of days more without access to my HA enviroment, you are free to make suggestions and add to that. I will be closing this issue now that the project us underway. If you wish to contribute just feel free to push it my way!
