### ISSUE TITLE
Departure sensor without the need of a si2key

### ISSUE THREAD

**Issue by christophebaraer** [DSorlov/hasl-platform#51]
Hej and thank you for the great component! 

According to the documentation, the use of the `si2key` is optional and doesn't seem needed for the Departures sensor. However not adding it results in the following error

```
Log Details (ERROR)
Thu Dec 05 2019 10:53:40 GMT+0100 (Central European Standard Time)
Error while setting up platform hasl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hasl/sensor.py", line 138, in setup_platform
    config.get(CONF_USE_MINIMIZATION)
  File "/config/custom_components/hasl/sensor.py", line 492, in __init__
    if self._si2key:
AttributeError: 'SLDeparturesSensor' object has no attribute '_si2key'
```

Would it be possible to list of the upcoming departures without listing disturbances related to the  SL Störningsinformation 2 API ?

Tack!

**Comment by DSorlov** [comment]
Verified and will be adressed

**Comment by christophebaraer** [comment]
Thanks Daniel.

**Comment by DSorlov** [comment]
In the new version 3 this is changed in the way that the departure sensor handles deviations. The deviations will be handled in a separate integration but will use a common datasource if it is available. Therefore this will be closed for now. Please keep an eye out for v3.
