### ISSUE TITLE
HASL_API_Error 1002: API key is invalid

### ISSUE THREAD

**Issue by sesapriv** [DSorlov/hasl-platform#52]
Hello.

I'm having problem using services

hasl.find_trip_pos
hasl.find_location
hasl.find_trip_id

Error: HASL_API_Error 1002: API key is invalid

Not 100% sure where to put pu1key and tp3key. In the docs it's supposed to be added to configuration.yaml

my configuration.yaml
hasl:
  tp3key: MY KEY

Sensors works like a charm!

**Comment by DSorlov** [comment]
The keys are indeed supposed to be added into configuration.yaml
Have you verified that the key is valid?
Also; are you able to see any more information in logs either local or in API?
Just FYI this services are still early and not deemed stable.

**Comment by sesapriv** [comment]
I have checked the API key, its correct. Hassio do not like hasl statement in configuration.yaml.

I see this in logs:

Invalid config for [hasl]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 276)

Line 276 in my configuration.yaml

hasl:
    tp3key: KEY

Hassio version 0.103.3.

**Comment by DSorlov** [comment]
We are currently deep into rewriting for v3 which will be configurable via GUI. This issue will be adressed in that codebase and that is why I will close this ticket.
