### ISSUE TITLE
API returns 404 via HASL because of no master branch

### ISSUE THREAD

**Issue by lindell** [DSorlov/hasl-platform#53]
Detected by HACS giving this error message:
```
2020-02-12 20:28:42 ERROR (MainThread) [hacs] Validation for DSorlov/hasl-platform failed with GitHub returned 404 for https://api.github.com/repos/DSorlov/hasl-platform/git/trees/master.
```

https://api.github.com/repos/DSorlov/hasl-platform/git/trees/master

It seems to be because there exist no `master` branch. Maybe it could be added?

**Comment by heisenberg2980** [comment]
Same issue here

**Comment by dimmanramone** [comment]
@lindell @elbueno222  I'll take a look as soon as I can and probably create a master branch

**Comment by dimmanramone** [comment]
@lindell @elbueno222 I created a master branch, unfortunately I cannot make it defaults because I don't have all the permissions in thre repo. But you are welcome to test if it is working for you now.

**Comment by lindell** [comment]
I don't get the warning any more :)

**Comment by heisenberg2980** [comment]
> @lindell @elbueno222 I created a master branch, unfortunately I cannot make it defaults because I don't have all the permissions in thre repo. But you are welcome to test if it is working for you now.

I am not getting the warning anymore, than you very much!!
