### ISSUE TITLE
Error in tap_action after upgrade to HA 0.107

### ISSUE THREAD

**Issue by tomoqv** [DSorlov/hasl-platform#54]
Hi,
just got a problem with the HASL-card and tap_action after my latest upgrade of HA. This is the lovelace error message:
```
can't define property "tap_action_entity": Object is not extensible

type: 'custom:hasl-departure-card'
show_cardname: false
header: false
departures: true
timeleft: false
updated: false
offset: 5
hide_departed: true
language: sv-SE
entities:
  - sensor.mossens_ip
  - sensor.alleparken
style: |
  ha-card {
    font-size: 1.2em;
    # height: 150px;
    # width: 300px;
    # margin-top: 0px;
    # margin-bottom: 0px;
  }
tap_action: service
service_config:
  domain: browser_mod
  service: popup
  data:
    title: Avgångar
    card:
      type: 'custom:hasl-departure-card'
      header: false
      departures: true
      deviations: true
      timeleft: false
      updated: true
      name: Tidtabeller
      hide_departed: true
      language: sv-SE
      entities:
        - sensor.alleparken
        - sensor.mossens_ip
        - sensor.alviks_strand
        - sensor.alvik
    deviceID:
      - this

```
Any idea?

**Comment by dimmanramone** [comment]
@tomoqv This should be a hasl departure card problem. Can you report it [there](https://github.com/hasl-platform/lovelace-hasl-departure-card) instead? 

I'll try to reproduce it. Are you on the latest 0.107?

**Comment by dimmanramone** [comment]
@tomoqv Just test that with almost identical configuration like yours. Seems to work fine for me. Are you on latest 0.107.6 and the latest browser_mod?

**Comment by tomoqv** [comment]
Sorry, will report it in the right place. I am on HA 0.107.5 and upgrading to 0.107.6 now. Just noticed that I have not installed HASL departure card through the community store before. Have done that as well. It still doesn't work. Do I need to remove code from my lovelace resources after that?

**Comment by tomoqv** [comment]
I have now posted in the [right place](https://github.com/hasl-platform/lovelace-hasl-departure-card/issues/9), so let's continue the discussion there. Thanks
