### ISSUE TITLE
TimeWindow

### ISSUE THREAD

**Issue by nesalkiN** [DSorlov/hasl-platform#6]
Could TimeWindow be user controlled? It seems like standard = 30 min.
My bus stop has 1 or 2 departures every hour. Would like to set TimeWindow=60 (max).
https://www.trafiklab.se/node/15754/documentation

I'm also a bit interested in how useful it is to see "x min" when last update could be 5 minutes old? How do people use this? Like now, I see 20 min but it was fetched 9 minutes ago. Could it be optional to just show next departure time (going by scheduled time)? Looks like "TimeTabledDateTime" and/or "ExpectedDateTime" (ExpectedDateTime would be more near real time?) should have that data. Like option to show time from DisplayTime, TimeTabledDateTime or ExpectedDateTime.

**Comment by DSorlov** [comment]
I have for now selected to implement the TimeWindow in the next release, it will be 30 minutes by default but user configurable from 5 to 60 minutes.
The reason for not getting time table data but instead using realtime is that when larger disturbances occur it is more correct. The refresh time can also be set from next version to as low as one minute which will allow those who have the right api-access direct data and for people like me having not so many buses per hour the "approximate" real-time.

**Comment by nesalkiN** [comment]
Ok, good. Thanks!
About the time. What I want is to always show the time and never "x min" or "Nu". The disturbance detection could be unchanged? Too bad I don't know python. ;)

**Comment by DSorlov** [comment]
Aha! That would involve some more coding as the time is actually sent as X min or Nu from the real-time API and not as timestamps.. I guess it could be done, I will hold it open for now and see if I get any bright ideas if it could be solved and if so how..

**Comment by nesalkiN** [comment]
The response from the api should have two times that could be used. Just guessing. ;)
TimeTabledDateTime or ExpectedDateTime. ExpectedDateTime seem to be the time close to realtime

Edit: Like this bus from Hallonbergen just now 23:25 (using https://www.trafiklab.se/node/15754/console)

"TimeTabledDateTime": "2019-04-11T23:25:00",
**"ExpectedDateTime": "2019-04-11T23:31:07",**
"DisplayTime": "6 min",

It's late. :D

**Comment by DSorlov** [comment]
I tried using them before and I had some problems with them beeing null during some occations; As I understand from the API it can be null if there is disturbances and then I would need to handle those cases also. Again; not impossible, but I have more been thinking of the script as a digital departure board rather than a timetable.. but I guess one could do some switch for that.. but right now #sleep! =) I will update as soon as I get around looking at this, doing a major rewrite right now so concentrating on that.. and work.. and life..  =)

**Comment by nesalkiN** [comment]
Now I glance at the card and see "8 min", thinking "Nice! I can catch that bus" just to see that the information is 9 minutes old. Most will not have access to the higher api levels. For it to work as a departure board, we will need updates at least every minute.

You could calculate the time to show using the DisplayTime value too (Now + x min) but yeah, more coding and it will depend on the user system clock. More code, less life. ;) 

Thanks for considering! God natt!

**Comment by DSorlov** [comment]
You won. Implemented in new code, will upload here soon! =)
