### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'hasl'. 

### ISSUE THREAD

**Issue by MrChunks** [DSorlov/hasl-platform#61]
I am starting to receive this error in the logs:

_No 'version' key in the manifest file for custom integration 'hasl'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'hasl'_

I'm not a developer, so this is probably unnecessary, but I found some discussion about this warning/pending change/error: https://community.home-assistant.io/t/no-version-key-in-the-manifest-file-for-custom-integration-ha-2021-3-0/286487/16

**Comment by DSorlov** [comment]
Will look into this asap however in hospital due to covid so not very able right now, any assistance appreciated

**Comment by MrChunks** [comment]
That's terrible.. I hope you are on the path to recovery.

Before I saw your reply, I wanted to add that it was listed in the "breaking changes" for "custom components" in the next release here: https://www.home-assistant.io/blog/2021/05/05/release-20215/#breaking-changes 

I'm not really a developer though I tinker, maybe I can see if I can figure out what needs to be done. It seems to be fairly straight forward.

Again, I hope you feel better soon.

**Comment by DSorlov** [comment]
@dimmanramone thanks for the fix! 

I am still on recovery but it is going in the right direction. thanks for your patience!

**Comment by dimmanramone** [comment]
@DSorlov Your welcome. Hope you are doing better. Krya på dig!
