### ISSUE TITLE
tzinfo error

### ISSUE THREAD

**Issue by fatuuse** [DSorlov/hasl-platform#63]
## System Health

version | core-2021.6.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 4.4.59+
arch | x86_64
timezone | Europe/Stockholm

Home Assistant SL Sensor (HASL) 2.2.5
```
2021-06-03 09:21:11 ERROR (SyncWorker_6) [custom_components.hasl.sensor] A error occured while updating SI2 sensor: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
2021-06-03 09:21:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.slussen fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/hasl/sensor.py", line 674, in _update
    self._lastupdate = now(self._hass.config.time_zone)
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 66, in now
    return dt.datetime.now(time_zone or DEFAULT_TIME_ZONE)
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
```

**Comment by dimmanramone** [comment]
@fatuuse It seems that is related with the new timezone settings in HA Core https://github.com/home-assistant/core/issues/51385

**Comment by fatuuse** [comment]
```pip install tzdata``` solved error.

**Comment by CJA85** [comment]
also having this issue, just switched to HASL since old SL integration seemed to fault, but looks like its a timezone error.

Awaiting fix ;) great integration!

**Comment by CJA85** [comment]
fyi, running on docker, and having this issue.

**Comment by DSorlov** [comment]
> @fatuuse It seems that is related with the new timezone settings in HA Core [home-assistant/core#51385](https://github.com/home-assistant/core/issues/51385)

Yepp. Seems like this matches. I dont have access to my build environment, but adding should solve it. Coud @CJA85  or @fatuuse  confirm that it will work once tzdata is installed (python3 -m pip install tzdata). If so we could move forward and either add it as a requirement or perhaps just mention it in the install docs as it does not seem to affect all platforms?

**Comment by fatuuse** [comment]
Pip install don't solve problem. 
Still same error...
And the requirement were already satisfied by other component.

**Comment by CJA85** [comment]
What fatuuse said, does not work

**Comment by DSorlov** [comment]
Ok; this is actually a change in how the lib works I think; I still do not have access to my build machine but will try and work on it next week if no-one else have time before that.

**Comment by gamvik** [comment]
I am definitely no expert on programming for Home Assistant, and have never programmed anything in Python.
I managed to get it working by replacing all calls to `now(self._hass.config.time_zone)` with just `now()`, which would work according to the documentation: `datetime.now(tz=None)`, where "tz" is optional) . I don't know if this is the correct way of doing it though.

**Comment by DSorlov** [comment]
Seems like a good workaround. This is most likely correct way since the change in api. I eill confirm and submit pr if noone beats me to it.

Thanks my @gamvik #andnowwemeetagain :)

**Comment by dimmanramone** [comment]
@DSorlov Just tested and works for me too. I can make a PR with the workaround.

Just pushed in dev

**Comment by DSorlov** [comment]
New version merged and released. Will close this thread now. Please open new issue if new problems arise.
https://github.com/DSorlov/hasl-platform/releases/tag/2.2.7

Huge thanks to @dimmanramone to the rescue once more, and to @gamvik for drawing up the solution for us, and to @CJA85 and @fatuuse for testing the first workaround suggestion! Great teamwork everyone! =)
