### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by lawi75** [DSorlov/hasl-platform#66]
No updates for over 6 months... And pull requests with valid fixes for for example filtering is just waiting

**Comment by DSorlov** [comment]
Absolutely not dead. I cannot see any submissions that have not been handled. Are you in the right repo?

**Comment by DSorlov** [comment]
Aha! I think this is related to the integration (hasl3) beta. I just decided that the change was to small to be pushed by itself. But perhaps its been waiting long enough and I can push it even if its a small fix to the beta. :)

**Comment by lawi75** [comment]
Super :-)
