### ISSUE TITLE
interval and some stuff in readme.

### ISSUE THREAD

**Issue by nesalkiN** [DSorlov/hasl-platform#7]
Hello,

Thanks for the time display. :) Working good!
Updates seem to fire every 10 min (default, readme say 5)

Adding "interval: 5" to config gives me this:
"Your configuration contains extra keys that the platform does not support.
Please remove [interval].  (See /config/configuration.yaml, line 120)."

URLs for custom_updater need to be changed to the new location (hasl).

**Comment by DSorlov** [comment]
Fixed. This was due to a update where I have changed the INTERVAL to SCAN_INTERVAL to better align with HomeAssistant naming.

Due to the number of changes and breaking arguments I will not update old branch with the new location for custom_updater, there is new files in the new branch.
