### ISSUE TITLE
Line filter visar felaktig linje

### ISSUE THREAD

**Issue by jacoblo** [DSorlov/hasl-platform#71]
- När angett line (54) även annan (4) upp.
- Filtret fungerar och rensar flera andra linjer som den ska. Så fungerar delvis samt direction men buss 4 som inte ska vara med.

![FI-QcakWUAghGxj](https://user-images.githubusercontent.com/18484639/149328745-70894234-8606-4646-b94d-afdebfb17f15.jpeg)
![FI-QbmAXwAI2wZT](https://user-images.githubusercontent.com/18484639/149328753-b8147821-b3ec-483c-86a6-f0077208d98e.png)

**Comment by DSorlov** [comment]
Could you please open this issue at HASL-Platform/Integration as it is not valid for this branch.
This repo is for the EOL 2.x, sorry for not being able to automatically move it.

Please go to https://github.com/hasl-sensor/integration/issues
