### ISSUE TITLE
No new version in custom_updater

### ISSUE THREAD

**Issue by folrewef** [DSorlov/hasl-platform#8]
In my case the custom updater still shows v0.0.8 and no need to update.

**Comment by nesalkiN** [comment]
You need to change the "dev" part in the urls to "hasl" for it to pick up the new version.

 component_urls:
    - https://raw.githubusercontent.com/DSorlov/ha-sensor-sl/hasl/custom_updater.json
  card_urls:
    - https://raw.githubusercontent.com/DSorlov/ha-sensor-sl/hasl/custom_cards.json

**Comment by DSorlov** [comment]
As @NiklasOlofsson above stated you need to change the URL. Sorry about this as I did not think about that specific consequence but as there is breaking changes I will not update the old version repository even if that is possible.

**Comment by folrewef** [comment]
No probs - just changed my urls
